name: Scan secrets with Infisical

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Infisical CLI
        run: |
          curl -1sLf "https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh" | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      - name: Debug Infisical Secrets (Optional)
        env:
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
        run: |
          infisical run --env=development printenv

      - name: Scan for exposed secrets
        env:
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
        run: |
          infisical scan --no-git --source . --verbose --report-path report.json

      - name: Output scan results
        run: |
          cat report.json

      - name: Upload scan report
        uses: actions/upload-artifact@v3
        with:
          name: infisical-scan-report
          path: report.json

